# Generated by Django 5.0.6 on 2024-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
